# you can define explicit location of docker executable
# or use autodetect executable feature
# executable="${DOCKER_HOME}/docker"

[alias]
dangling_images="images -f dangling=true -q"
stopped_containers="ps -f status=exited -q"
running_containers="ps -f status=running -q"
stopall="!docker running_containers | xargs -n 1 docker stop"
psn="ps --format=\"{{.Names}}\""
prune_all="system prune -a"
purge="!docker prune_all"

[alias.gc] # garbage collector
i="!docker dangling_images | xargs -n 1 docker rmi" # remove dangling images
c="!docker stopped_containers | xargs -n 1 docker rm" # remove stopped containers

